# frozen_string_literal: true

require "fileutils"
require "pathname"

APPRAISAL2_ROOT = File.expand_path("../../appraisal-rb/appraisal2", __dir__)
$LOAD_PATH.unshift(File.join(APPRAISAL2_ROOT, "lib"))

require "appraisal/appraisal_file"

STAGE = File.expand_path("tmp/stage", __dir__)
FileUtils.rm_rf(STAGE)
FileUtils.mkdir_p(STAGE)

def write(path, content)
  full_path = File.join(STAGE, path)
  FileUtils.mkdir_p(File.dirname(full_path))
  File.write(full_path, content)
end

def generated(path)
  File.read(File.join(STAGE, path)).strip
end

def generate
  Dir.chdir(STAGE) do
    Appraisal::AppraisalFile.each(&:write_gemfile)
  end
end

write "Gemfile", <<~GEMFILE
  source "https://gem.coop"
  git_source(:custom_git_source) { |repo| "../build/\#{repo}" }
  ruby "#{RUBY_VERSION}"

  gem "bagel"
  gem "croissant", :custom_git_source => "croissant"

  git "../build/egg" do
    gem "egg"
  end

  path "../build/waffle" do
    gem "waffle"
  end

  group :breakfast do
    gem "orange_juice"
    gem "omelette", :custom_git_source => "omelette"
    gem "rotten_egg"
  end

  platforms :ruby, :jruby do
    gem "milk"
    group :lunch do
      gem "coffee"
    end
  end

  source "https://other-rubygems.org" do
    gem "sausage"
  end

  install_if '"-> { true }"' do
    gem "mayonnaise"
  end
GEMFILE

write "Appraisals", <<~APPRAISALS
  appraise "breakfast" do
    source "http://some-other-source.com"
    ruby "1.8.7"

    gem "bread"
    gem "pain_au_chocolat", :custom_git_source => "pain_au_chocolat"

    git "../build/egg" do
      gem "porched_egg"
    end

    path "../build/waffle" do
      gem "chocolate_waffle"
    end

    group :breakfast do
      remove_gem "rotten_egg"
      gem "bacon"
      platforms :rbx do
        gem "ham"
      end
    end

    platforms :ruby, :jruby do
      gem "yoghurt"
    end

    source "https://other-rubygems.org" do
      gem "pancake"
    end

    install_if "-> { true }" do
      gem "ketchup"
    end

    gemspec
    gemspec :path => "sitepress"
  end
APPRAISALS

expected = <<~GEMFILE.strip
  # This file was generated by Appraisal2

  source "https://gem.coop"
  source "http://some-other-source.com"

  ruby "1.8.7"

  git "../../build/egg" do
    gem "egg"
    gem "porched_egg"
  end

  path "../../build/waffle" do
    gem "waffle"
    gem "chocolate_waffle"
  end

  gem "bagel"
  gem "croissant", :git => "../../build/croissant"
  gem "bread"
  gem "pain_au_chocolat", :git => "../../build/pain_au_chocolat"

  group :breakfast do
    gem "orange_juice"
    gem "omelette", :git => "../../build/omelette"
    gem "bacon"

    platforms :rbx do
      gem "ham"
    end
  end

  platforms :ruby, :jruby do
    gem "milk"
    gem "yoghurt"

    group :lunch do
      gem "coffee"
    end
  end

  source "https://other-rubygems.org" do
    gem "sausage"
    gem "pancake"
  end

  install_if -> { true } do
    gem "mayonnaise"
    gem "ketchup"
  end

  gemspec :path => "../"
  gemspec :path => "../sitepress"
GEMFILE

begin
  generate
  actual = generated("gemfiles/breakfast.gemfile")
  if actual == expected
    puts "PASS no active issue: Appraisal2 DSL generation matched expected output"
  else
    puts "CURRENT ISSUE: generated Appraisal2 DSL output differed"
    puts "--- expected"
    puts expected
    puts "--- actual"
    puts actual
    exit 2
  end
rescue StandardError => e
  puts "CURRENT ISSUE: Appraisal2 DSL generation raised on #{RUBY_ENGINE}"
  puts "#{e.class}: #{e.message}"
  puts e.backtrace.first(12)
  exit 2
end
